### ISSUE TITLE
Error keeps happening when i import file or use cli

### ISSUE THREAD

**Issue by betawarrior12** [mmabrouk/chatgpt-wrapper#102]
Traceback (most recent call last):
  File "C:\Users\USER\Pemi\PYTHON\Projects\Made\chat\chat.py", line 101, in <module>
    import chatgpt_wrapper
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\chatgpt_wrapper\__init__.py", line 1, in <module>
    from .chatgpt import ChatGPT
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 10, in <module>
    from playwright.sync_api import sync_playwright
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "C:\Users\USER\AppData\Local\Programs\Python\Python3.8.10\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: The specified module could not be found.

**Comment by alphaokxyz** [comment]
same,any Solution？

**Comment by udps** [comment]
I would recommend three potential solutions, although I am not sure which will ultimately resolve the issue, if at all

- Reinstall the greenlet module
- Verify that all required dependencies are installed properly
- Update Python

Other than that, this from that traceback anove, I can barely conclude anything from above traceback. Hope it helps nonetheless 👍

**Comment by betawarrior12** [comment]
Thanks
