### ISSUE TITLE
ImportError: DLL load failed while importing _greenlet

### ISSUE THREAD

**Issue by alphaokxyz** [mmabrouk/chatgpt-wrapper#131]
C:\file>chatgpt install
Traceback (most recent call last):
  File "C:\Software\Python\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.17', 'console_scripts', 'chatgpt')())
  File "C:\Software\Python\Scripts\chatgpt-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\software\python\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\software\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\software\python\lib\site-packages\chatgpt_wrapper\__init__.py", line 1, in <module>
    from .chatgpt import ChatGPT
  File "c:\software\python\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 13, in <module>
    from playwright.sync_api import sync_playwright
  File "c:\software\python\lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "c:\software\python\lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "c:\software\python\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "c:\software\python\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "c:\software\python\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: 找不到指定的模块。

**Comment by thehunmonkgroup** [comment]
Browser backend has been deprecated, suggest you use the API backend.
