### ISSUE TITLE
chatgpt always exits with exception `failed to set title`

### ISSUE THREAD

**Issue by gyliu513** [mmabrouk/chatgpt-wrapper#138]
```console
% chatgpt
Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> go code for binary search

Sure, here's an example implementation of binary search in Go:

```
package main

import (
    "fmt"
)

// BinarySearch searches for a target value in a sorted slice of integers
func BinarySearch(arr []int, target int) int {
    left := 0
    right := len(arr) - 1

    for left <= right {
        mid := (left + right) / 2

        if arr[mid] == target {
            return mid
        } else if arr[mid] < target {
            left = mid + 1
        } else {
            right = mid - 1
        }
    }

    return -1
}

func main() {
    arr := []int{1, 3, 5, 7, 9}
    target := 5

    index := BinarySearch(arr, target)

    if index == -1 {
        fmt.Println("Target not found in slice")
    } else {
        fmt.Printf("Target found at index %d\n", index)
    }
}
```

This implementation takes a sorted slice of integers `arr` and a target value `target` as input, and returns the index of the target value in the slice if it exists. If the target value is not found in the slice, it returns -1.

The implementation works by initializing two pointers, `left` and `right`, to the start and end of the slice respectively. It then repeatedly calculates the midpoint of the slice using integer division, and checks whether the value at the midpoint is equal to, greater than, or less than the target value. Based on the result of this comparison, it updates the `left` or `right` pointer to focus on the appropriate half of the slice, and repeats the process until either the target value is found or the pointers cross each other, indicating that the target value is not present in the slice.Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/main.py", line 79, in main
    shell.cmdloop()
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/gpt_shell.py", line 148, in do_ask
    return self.default(line)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/gpt_shell.py", line 157, in default
    for chunk in self.chatgpt.ask_stream(line):
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/chatgpt.py", line 303, in ask_stream
    self._set_title()
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/chatgpt.py", line 149, in _set_title
    raise Exception(f"Failed to set title: {response.status} {response.status_text} {response.headers}")
Exception: Failed to set title: 403 Forbidden {'date': 'Thu, 23 Feb 2023 21:17:30 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '79e2fd1a7e84b04e-ATL', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
```

**Comment by thehunmonkgroup** [comment]
See https://github.com/mmabrouk/chatgpt-wrapper/issues/133#issuecomment-1442457484

**Comment by thehunmonkgroup** [comment]
If you've experienced this issue, it would be extremely helpful if you could offer more information to the developers about your setup, see the bottom of the original issue post at #142 for more info
