### ISSUE TITLE
Installation isuue

### ISSUE THREAD

**Issue by farzaneh74** [mmabrouk/chatgpt-wrapper#146]
when I want to install chatgpt using this command: chatgpt install, I got the following error

Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_wrapper/main.py", line 78, in main
    chatgpt = ChatGPT(headless=not (install_mode or args.debug), timeout=90, **extra_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_wrapper/chatgpt.py", line 56, in __init__
    shutil.copytree("/tmp/playwright", self.user_data_dir)
  File "/usr/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/playwright/lock', '/tmp/7cfd4e1a-a586-4fd1-a65e-a0081a0f9a4d/lock', "[Errno 2] No such file or directory: '/tmp/playwright/lock'")]
How can I fix it?

**Comment by mmabrouk** [comment]
do 'rm -r /tmp/playwright/' then make sure all chatgpt_wrapper running instances are killed and try again

**Comment by farzaneh74** [comment]
I removed this file and all dependencies of chatgpt wrapper. Now after chatgpt install commend, the following error appeard:

usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 5, in <module>
    from chatgpt_wrapper.main import main
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_wrapper/__init__.py", line 1, in <module>
    from .chatgpt import ChatGPT
  File "/usr/local/lib/python3.8/dist-packages/chatgpt_wrapper/chatgpt.py", line 14, in <module>
    from playwright.sync_api import sync_playwright
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 24, in <module>
    from pyee import EventEmitter
  File "/usr/local/lib/python3.8/dist-packages/pyee/__init__.py", line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "/usr/local/lib/python3.8/dist-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/usr/local/lib/python3.8/dist-packages/trio/__init__.py", line 76, in <module>
    from ._dtls import DTLSEndpoint, DTLSChannel
  File "/usr/local/lib/python3.8/dist-packages/trio/_dtls.py", line 136, in <module>
    @attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'

**Comment by mmabrouk** [comment]
no clue what is this. I would try to uninstall playwright and reinstall (both the pip module and firefox)

**Comment by thehunmonkgroup** [comment]
Closing due to inactivity.
