### ISSUE TITLE
Chatgpt fails on listing history or any options over VPN

### ISSUE THREAD

**Issue by eralgua** [mmabrouk/chatgpt-wrapper#176]
I'm seeing below error when I try to run the wrapper from the corporate vpn. if I try to run the chatgpt using playwright browser that works without any issues. I'm wondering if it is something specific to network blocking on vpn or it can be related to "CORS" as below IP address refusing connection is of Cloudflare.

```
❯ chatgpt install
Install mode: Log in to ChatGPT in the browser that pops up, and click
through all the dialogs, etc. Once that is achieved, exit and restart
this program without the 'install' parameter.

Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> !history

 • Fetching conversation history...

Traceback (most recent call last):
  File "/Users/user1/Development/tools/python/venv/personal/bin/chatgpt", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.17', 'console_scripts', 'chatgpt')())
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/chatgpt_wrapper/main.py", line 88, in main
    shell.cmdloop()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/chatgpt_wrapper/gpt_shell.py", line 250, in do_history
    history = self._fetch_history(limit=limit, offset=offset)
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/chatgpt_wrapper/gpt_shell.py", line 163, in _fetch_history
    history = self.chatgpt.get_history(limit=limit, offset=offset)
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 234, in get_history
    ok, json, response = self._api_get_request(url, query_params)
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 154, in _api_get_request
    response = self.page.request.get(url, headers=headers, params=query_params)
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 18188, in get
    self._sync(
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 167, in get
    return await self.fetch(
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 285, in fetch
    return await self._inner_fetch(
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_fetch.py", line 372, in _inner_fetch
    response = await self._channel.send(
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/Users/user1/Development/tools/python/venv/personal/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: connect ECONNREFUSED 104.18.3.161:443
```

**Comment by thehunmonkgroup** [comment]
Browser backend makes standard REST requests to `chat.openai.com`, so any issues are most likely firewall related.
