### ISSUE TITLE
v0.4.1 async for type error

### ISSUE THREAD

**Issue by jevgenij-breachgg** [mmabrouk/chatgpt-wrapper#185]
Hi,
wrapper worked super before the last updates: 
Using a simple script: 

from chatgpt_wrapper import ChatGPT

bot = ChatGPT()
response = bot.ask("Hello, world!")
print (response)

Now get an error:

Traceback (most recent call last):
  File "C:\PycharmProjects\dialog_bot_test\test\ask_gpt.py", line 4, in <module>
    response = bot.ask("Hello, world!")
  File "C:\PycharmProjects\dialog_bot_test\venv\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 503, in ask
    return asyncio.run(super().ask(message))
  File "C:\PycharmProjects\dialog_bot_test\venv\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "C:\PycharmProjects\dialog_bot_test\venv\lib\site-packages\nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "C:\Program Files\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\PycharmProjects\dialog_bot_test\venv\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 463, in ask
    response = list([i async for i in self.ask_stream(message)])
TypeError: 'async for' requires an object with __aiter__ method, got generator

**Comment by Mrw33554432** [comment]
Exactly same error

**Comment by jevgenij-breachgg** [comment]
Rolled back to v0.3.17

**Comment by Mrw33554432** [comment]
> Rolled back to v0.3.17

Sorry man but what is the command to install v0.3.17. I tried it with both == and @ but none of those two method works

**Comment by jevgenij-breachgg** [comment]
I just used previous commits 
pip install --upgrade git+https://github.com/mmabrouk/chatgpt-wrapper@9a87bc3c623e4940dc8e784eceb7029a23ca1ce5

**Comment by thehunmonkgroup** [comment]
BTW, the `AsyncChatGPT` class is now exposed in the base module, and that is working, see example code here: https://github.com/mmabrouk/chatgpt-wrapper/issues/191#issuecomment-1450470350

**Comment by jevgenij-breachgg** [comment]
@thehunmonkgroup thank you.

**Comment by thehunmonkgroup** [comment]
Pretty sure this is fixed. If not, reopen
