### ISSUE TITLE
[err] This profile was last used with a newer version of this application. Please create a new profile.

### ISSUE THREAD

**Issue by mindgitrwx** [mmabrouk/chatgpt-wrapper#188]
Unexpected playwright error after second reinstall

chatgpt version 0.4.1

```
jhyeo@jhyeoui-MacBookPro ~ % chatgpt
Traceback (most recent call last):
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 56, in create
    self.browser = await playbrowser.launch_persistent_context(
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/playwright/async_api/_generated.py", line 14251, in launch_persistent_context
    await self._impl_obj.launch_persistent_context(
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_browser_type.py", line 155, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/Users/jhyeo/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
playwright._impl._api_types.Error: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /Users/jhyeo/Library/Caches/ms-playwright/firefox-1369/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -headless -profile /tmp/playwright -juggler-pipe about:blank
<launched> pid=2324
[pid=2324][err] *** You are running in headless mode.
[pid=2324][err] This profile was last used with a newer version of this application. Please create a new profile.
[pid=2324] <process did exit: exitCode=0, signal=null>
[pid=2324] starting temporary directories cleanup

```

**Comment by mmabrouk** [comment]
try rm -r /tmp/playwright then reinstalling

**Comment by thehunmonkgroup** [comment]
Closing due to inactivity.

**Comment by avijay6** [comment]
> try rm -r /tmp/playwright then reinstalling

This worked for me

**Comment by thehunmonkgroup** [comment]
There is a `chatgpt reinstall` command that wipes your existing profile, probably a little easier and cleaner.

**Comment by avijay6** [comment]
great
