### ISSUE TITLE
ChatGPT report "RuntimeError: There is no current event loop in thread 'Thread-2'."

### ISSUE THREAD

**Issue by gyliu513** [mmabrouk/chatgpt-wrapper#192]
I was following this blog https://www.pragnakalp.com/build-an-automated-ai-powered-slack-chatbot-with-chatgpt-using-flask/ to build a slack bot to integrate with ChatGPT, but encounter one issue as follows:

- My code
```python
import slack
import os, signal

from flask import request
from flask import Flask
from chatgpt_wrapper import ChatGPT
from slackeventsapi import SlackEventAdapter

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

SLACK_TOKEN="xoxb-xxxx"
SIGNING_SECRET="xxxxx"

app = Flask(__name__)
slack_event_adapter = SlackEventAdapter(SIGNING_SECRET, '/slack/events', app)

def process():
    try:

        # iterating through each instance of the process
        for line in os.popen("ps ax | grep firefox | grep -v grep"):
            print(line, ">>>>>>>>>>>>")
            fields = line.split()

            # extracting Process ID from the output
            pid = fields[0]

            # terminating process
            os.kill(int(pid), signal.SIGKILL)
        print("Process Successfully terminated")

    except:
        print("Error Encountered while running script")

@ slack_event_adapter.on('message')
def message(payload):
    print(payload)
    client = slack.WebClient(token=SLACK_TOKEN)

    try:
        if request.method == 'POST':
            event = payload.get('event', {})

            if event['client_msg_id']:
                channel_id = event.get('channel')
                user_id = event.get('user')
                text = event.get('text')
                print(text)
                if text == "hi":
                  client.chat_postMessage(channel=channel_id,text="Hello")
                print("Before create chatgpt bot")
                bot = ChatGPT()
                print("After create chatgpt bot")
                print("Before ask chatgpt")
                chatbot_res = bot.ask(text)
                print("After ask chatgpt")
                print("Before process")
                # process()
                print("After process")
                print("ChatGPT Response=>",chatbot_res)
                client.chat_postMessage(channel=channel_id,text=chatbot_res)

                return chatbot_res

    except Exception as e:
        print(e)
        pass
    return '200 OK HTTPS.'

if __name__ == "__main__":
    app.run(debug=True, use_reloader=True, port=3001)
```

- Run the code with configuration and send `hi` to my slack channel
```
{'token': 'd1NuXkuPZP5ZzNwlJCXLfYfB', 'team_id': 'T04QM5WFJ82', 'context_team_id': 'T04QM5WFJ82', 'context_enterprise_id': None, 'api_app_id': 'A04QMEM6999', 'event': {'client_msg_id': 'eae5fb20-a1c4-4d36-b60d-4017aa9d1203', 'type': 'message', 'text': 'hi', 'user': 'U04QM71MEJF', 'ts': '1677688343.948199', 'blocks': [{'type': 'rich_text', 'block_id': 'EAIX', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'hi'}]}]}], 'team': 'T04QM5WFJ82', 'channel': 'C04QMB7EF4K', 'event_ts': '1677688343.948199', 'channel_type': 'channel'}, 'type': 'event_callback', 'event_id': 'Ev04RW1N0VGA', 'event_time': 1677688343, 'authorizations': [{'enterprise_id': None, 'team_id': 'T04QM5WFJ82', 'user_id': 'U04R07MUY5P', 'is_bot': True, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '4-eyJldCI6Im1lc3NhZ2UiLCJ0aWQiOiJUMDRRTTVXRko4MiIsImFpZCI6IkEwNFFNRU02OTk5IiwiY2lkIjoiQzA0UU1CN0VGNEsifQ'}
hi
Before create chatgpt bot
signal only works in main thread of the main interpreter
127.0.0.1 - - [01/Mar/2023 11:32:24] "POST /slack/events HTTP/1.1" 200 -
{'token': 'd1NuXkuPZP5ZzNwlJCXLfYfB', 'team_id': 'T04QM5WFJ82', 'context_team_id': 'T04QM5WFJ82', 'context_enterprise_id': None, 'api_app_id': 'A04QMEM6999', 'event': {'bot_id': 'B04RB98P0SC', 'type': 'message', 'text': 'Hello', 'user': 'U04R07MUY5P', 'ts': '1677688344.576899', 'app_id': 'A04QMEM6999', 'blocks': [{'type': 'rich_text', 'block_id': '9n1R', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'Hello'}]}]}], 'team': 'T04QM5WFJ82', 'bot_profile': {'id': 'B04RB98P0SC', 'deleted': False, 'name': 'chatgptbot', 'updated': 1677009512, 'app_id': 'A04QMEM6999', 'icons': {'image_36': 'https://a.slack-edge.com/80588/img/plugins/app/bot_36.png', 'image_48': 'https://a.slack-edge.com/80588/img/plugins/app/bot_48.png', 'image_72': 'https://a.slack-edge.com/80588/img/plugins/app/service_72.png'}, 'team_id': 'T04QM5WFJ82'}, 'channel': 'C04QMB7EF4K', 'event_ts': '1677688344.576899', 'channel_type': 'channel'}, 'type': 'event_callback', 'event_id': 'Ev04SKMTQDBJ', 'event_time': 1677688344, 'authorizations': [{'enterprise_id': None, 'team_id': 'T04QM5WFJ82', 'user_id': 'U04R07MUY5P', 'is_bot': True, 'is_enterprise_install': False}], 'is_ext_shared_channel': False, 'event_context': '4-eyJldCI6Im1lc3NhZ2UiLCJ0aWQiOiJUMDRRTTVXRko4MiIsImFpZCI6IkEwNFFNRU02OTk5IiwiY2lkIjoiQzA0UU1CN0VGNEsifQ'}
'client_msg_id'
127.0.0.1 - - [01/Mar/2023 11:32:25] "POST /slack/events HTTP/1.1" 200 -
```
- Issue
Seems when call `bot = ChatGPT()`, the program failed due to `signal only works in main thread of the main interpreter`, can anyone share some insight here? Thanks!

**Comment by gyliu513** [comment]
app.run() with debug=False also does not work, but seems this works for someone else https://www.reddit.com/r/flask/comments/ewkvyd/flask_in_a_thread/

**Comment by gyliu513** [comment]
I updated to latest code for chatgpt-wrapper, and got different error now.

```
text is  hi
Before create chatgpt bot
There is no current event loop in thread 'Thread-2'.
/Users/guangyaliu/go/src/github.com/gyliu513/chatgptbot/3.py:71: RuntimeWarning: coroutine 'AsyncChatGPT.create' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function ChatGPT.__del__ at 0x103073dc0>
Traceback (most recent call last):
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 539, in __del__
    self.async_run(self.agpt.cleanup())
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 501, in async_run
    return asyncio.get_event_loop().run_until_complete(awaitable)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-2'.
/Users/guangyaliu/go/src/github.com/gyliu513/chatgptbot/3.py:71: RuntimeWarning: coroutine 'AsyncChatGPT.cleanup' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
127.0.0.1 - - [01/Mar/2023 14:45:45] "POST /slack/events HTTP/1.1" 200 -
```

**Comment by Mrw33554432** [comment]
I have a similar issue. As far as I know, the current version uses async and do not support multithread tasks.

**Comment by gyliu513** [comment]
Using the following version works:

```
pip install --upgrade git+https://github.com/mmabrouk/chatgpt-wrapper@9a87bc3c623e4940dc8e784eceb7029a23ca1ce5
```

**Comment by gyliu513** [comment]
close this one as it duplicate with https://github.com/mmabrouk/chatgpt-wrapper/issues/203
