### ISSUE TITLE
ChatGPT ask() return exception

### ISSUE THREAD

**Issue by gyliu513** [mmabrouk/chatgpt-wrapper#197]
I want to run the following python as an example

```python
from chatgpt_wrapper import ChatGPT

bot = ChatGPT()
# return the full result
response = bot.ask("tell me a story about cats and dogs")
print(response)

# return the result in streaming (chunks)
for chunk in bot.ask_stream("tell me a story about cats and dogs"):
    print(chunk)
```

But it failed when call ask()

```
Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from chatgpt_wrapper import ChatGPT
>>> bot = ChatGPT()

>>>
>>> response = bot.ask("tell me a story about cats and dogs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 521, in ask
    return asyncio.run(self.agpt.ask(message))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 477, in ask
    response = list([i async for i in self.ask_stream(message)])
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 477, in <listcomp>
    response = list([i async for i in self.ask_stream(message)])
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 306, in ask_stream
    await self.refresh_session()
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py", line 137, in refresh_session
    await self.page.goto("https://chat.openai.com/api/auth/session")
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/async_api/_generated.py", line 9162, in goto
    await self._impl_obj.goto(
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_page.py", line 494, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/Users/guangyaliu/Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 70, in inner_send
    done, _ = await asyncio.wait(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 411, in wait
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 411, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 671, in ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
```

**Comment by thehunmonkgroup** [comment]
You're running old code. Update 0.4.2

**Comment by gyliu513** [comment]
Thanks @thehunmonkgroup , it works now.

```python
from chatgpt_wrapper import ChatGPT
import time

prompt = "what is coronavirus? explain me in 2 3 lines"
bot = ChatGPT()
response = bot.ask(prompt)
print("Prompt: ",prompt)
print("Response: ",response)
```

```console
python3 4.py
Prompt:  what is coronavirus? explain me in 2 3 lines
Response:  Coronavirus is a family of viruses that can cause illness in animals and humans. The COVID-19 pandemic is caused by a new strain of coronavirus called SARS-CoV-2, which first emerged in Wuhan, China in 2019. Symptoms can range from mild to severe and include fever, cough, and difficulty breathing.
```
