### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by infinitel8p** [mmabrouk/chatgpt-wrapper#214]
Hi again, im getting another error when installing the wrapper on my surface:

```
pip install git+https://github.com/mmabrouk/chatgpt-wrapper 
Collecting git+https://github.com/mmabrouk/chatgpt-wrapper
  Cloning https://github.com/mmabrouk/chatgpt-wrapper to c:\users\ludo\appdata\local\temp\pip-req-build-k5u5azq7
  Running command git clone --filter=blob:none --quiet https://github.com/mmabrouk/chatgpt-wrapper 'C:\Users\Ludo\AppData\Local\Temp\pip-req-build-k5u5azq7'
  Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit 0cd8aa1e58e66bd2167aff8349859810308c61ed
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ludo\AppData\Local\Temp\pip-req-build-k5u5azq7\setup.py", line 9, in <module>
          setup(
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 488, in __init__
          _Distribution.__init__(
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 911, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 910, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\build_app.py", line 37, in <module>
          from py2app.create_appbundle import create_appbundle
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\create_appbundle.py", line 9, in <module>
          from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
        File "C:\Users\Ludo\AppData\Local\Programs\Python\Python310\lib\site-packages\py2app\util.py", line 5, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any idea how i can solve this?

**Comment by infinitel8p** [comment]
Fixed by updating from python `3.10` to `3.11.2`
