### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by martin-luecke** [mmabrouk/chatgpt-wrapper#229]
After first installation and changing the backend to `chatgpt-api`, chatgpt-wrapper tries to connect to the database instead of creating it. 
Note: sqlite is installed on the system 

<details>
  <summary>Here is the trace:</summary>
Traceback (most recent call last):

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 641, in connect
    return dialect.connect(*cargs, **cparams)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

</details>

**Comment by martin-luecke** [comment]
Ah, I don't believe it. Thank you for pointing this out, it lead me to the cause:
It was actually caused by the default database path of the  example config [here](https://github.com/mmabrouk/chatgpt-wrapper/blob/1f7c361c03cd1be03e32cd394af336b55c532bc7/config.sample.yaml#L11). I assumed `[username]` to be substituted with the currently logged in user. Putting `$USER` here as suggested in the section below did not work as well. I have used an explicit path and it works as expected now.


<details>
  <summary>For reference, here is the full trace</summary>

Traceback (most recent call last):

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 641, in connect
    return dialect.connect(*cargs, **cparams)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)

sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/martin/.local/bin/chatgpt", line 33, in <module>
    sys.exit(load_entry_point('chatGPT', 'console_scripts', 'chatgpt')())

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/main.py", line 17, in main
    asyncio.run(async_main())

  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/main.py", line 151, in async_main
    await shell.setup()

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/gpt_shell.py", line 398, in setup
    await self.configure_backend()

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/openai/api_shell.py", line 75, in configure_backend
    self.backend = AsyncOpenAIAPI(self.config)

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/openai/api.py", line 24, in __init__
    self.user_manager = UserManager(self.config)

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/openai/orm.py", line 276, in __init__
    self.orm = Orm(self.config)

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/openai/orm.py", line 107, in __init__
    self.engine, self.metadata = self.create_engine_and_metadata()

  File "/home/martin/development/misc/chatgpt-wrapper/chatgpt_wrapper/openai/orm.py", line 128, in create_engine_and_metadata
    metadata.reflect(bind=engine)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5475, in reflect
    with inspection.inspect(bind)._inspection_context() as insp:

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 111, in inspect
    ret = reg(subject)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 304, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 237, in _construct
    init(self, bind)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 248, in _init_engine
    engine.connect().close()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
    return self._connection_cls(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2413, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 641, in connect
    return dialect.connect(*cargs, **cparams)

  File "/home/martin/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
</details>

**Comment by thehunmonkgroup** [comment]
Glad you figured out the error.

> Putting `$USER` here as suggested in the section below did not work as well.

No idea what you mean here, are you maybe referring to the prompt substitution string? That's an entirely different functionality.

I will add a shouting comment to the test config that the line needs to be edited, or removed so the default value is used.
