### ISSUE TITLE
How to debug this project in IDE(PyCharm)?

### ISSUE THREAD

**Issue by kid9** [mmabrouk/chatgpt-wrapper#234]
I tried to run project in pycharm under the debug mode, but it failed to execute. error message is as follows:

Connected to pydev debugger (build 222.3739.56)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zhaoyan/Documents/code/chatgpt-wrapper/chatgpt_wrapper/openai/api_shell.py", line 8, in <module>
    from chatgpt_wrapper.openai.api import AsyncOpenAIAPI
  File "/Users/zhaoyan/Documents/code/chatgpt-wrapper/chatgpt_wrapper/openai/api.py", line 7, in <module>
    from openai.error import OpenAIError
ModuleNotFoundError: No module named 'openai.error'
python-BaseException

**Comment by thehunmonkgroup** [comment]
Looks like you don't have `openai` installed, or you have an older version.
