### ISSUE TITLE
passing prompt as first arguments cause a runtime error

### ISSUE THREAD

**Issue by ocontant** [mmabrouk/chatgpt-wrapper#265]
Reproduce: 
``` shell
$ chatGPT "test"

Is there anything specific you need assistance with?
```

Error thrown:
Exception in thread Thread-1 (gen_title_thread):
Traceback (most recent call last):
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/chatgpt_wrapper/backends/openai/api.py", line 135, in gen_title_thread
    loop.run_until_complete(self.gen_title_thread_async(conversation))
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/chatgpt_wrapper/backends/openai/api.py", line 122, in gen_title_thread_async
    success, completion, user_message = await self._call_openai_non_streaming(new_messages, temperature=0)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/chatgpt_wrapper/backends/openai/api.py", line 272, in _call_openai_non_streaming
    completion = await self._build_openai_chat_request(messages, temperature=temperature, top_p=top_p, presence_penalty=presence_penalty, frequency_penalty=frequency_penalty)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/chatgpt_wrapper/backends/openai/api.py", line 250, in _build_openai_chat_request
    response = await openai.ChatCompletion.acreate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 829, in run_in_executor
    executor.submit(func, *args), loop=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliviercontant/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

--------------------------------------------------------------

# ChatGPT wisdom about the error:

The error message suggests that the program attempted to schedule a new future after the Python interpreter had already been shut down. This can occur if the program was not properly cleaned up before it finished running, or if there was an issue with the way threads were created and managed in the program.

Based on the traceback, the error occurred in a multi-threaded Python program that uses the ChatGPT API wrapper. Specifically, it looks like an asynchronous function that is running in a separate thread attempted to create a new asyncio loop and schedule a new future after the main interpreter had already shut down. This could be caused by the thread not being properly terminated or by the thread attempting to perform an action that is not supported after the interpreter has been shut down.

To resolve the issue, you may need to review the code that uses the ChatGPT API wrapper and ensure that all threads are properly managed and terminated before the program exits. It may also be necessary to modify the way the threads are created or managed to prevent this error from occurring.

In the gen_title_thread method, a new event loop is being created and set as the current event loop for the current thread. However, the thread is not being properly closed after the loop has finished running. This can cause issues with subsequent async calls.

A better approach might be to use the asyncio.run() function to run the gen_title_thread_async() method instead of manually creating and managing an event loop. For example:

```python
async def gen_title(self, conversation):
    await self.gen_title_thread_async(conversation)
```

And then to call this method from your ask method, you can use:

```python
await self.gen_title(conversation)
```

This way, the gen_title method will be run in an event loop managed by asyncio.run(), which should avoid any conflicts with other event loops or threads.

---------------------------------------------------------------

# My limited feedback: 

I'm not familiar with multi-thread programming. But I think when I use chatGPT non interactively, it exit too fast, before all thread are completed. And the runtime is thrown because some thread completed after the interpreter has been shutdown.

**Comment by ocontant** [comment]
@thehunmonkgroup You closed without providing a feedback. 

This is a unmanaged crash. Would you mind elaborate before closing ?

**Comment by thehunmonkgroup** [comment]
Strange, I swear I provided a comment when I closed this.

At any rate, all async code has been removed from the project, it's likely this is no longer an issue with the latest code, so please try that, and reopen if it's still an issue.

**Comment by ocontant** [comment]
I did reinstall from git repo and the issue disapeared. 

May I ask why the async code was removed ? Was it because of entropy level  to manage ?

Also, is there a way to run an install directly from my local repository ? The documentation point to the github repo only. Not sure how to adapt the command to point to my local repo.

**Comment by ocontant** [comment]
Thank you very much! 
Have a good one! :)

**Comment by LakeishaKowalczyk** [comment]
@thehunmonkgroup
Hello, same here
I installed LWE in Docker

```
git clone https://github.com/llm-workflow-engine/llm-workflow-engine
sudo docker compose build && sudo docker compose up -d
sudo docker exec -it lwe-container /bin/bash -c "lwe"
```

```
[New Conversation]
(0.7/131072/0): default
self@c1 1> test

What specific aspect are you testing or curious about?

[Untitled]
(0.7/131072/34): default
self@c1 2> Exception in thread Thread-1 (gen_title_thread):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
    self._send_request_headers(**kwargs)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 151, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 983, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/src/lwe/backends/api/conversation_storage_manager.py", line 217, in gen_title_thread
    result = llm.invoke(new_messages)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 284, in invoke
    self.generate_prompt(
  File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 784, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 641, in generate
    raise e
  File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 631, in generate
    self._generate_with_cache(
  File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 853, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 688, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 704, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 947, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1007, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1007, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1017, in _request

[Untitled]
(0.7/131072/34): default
self@c1 2>
GoodBye!

openai.APIConnectionError: Connection error.
```

**Comment by thehunmonkgroup** [comment]
you appear to be using a non standard model configuration. show me the output of `/model` and `/config`

**Comment by LakeishaKowalczyk** [comment]
@thehunmonkgroup 
I'm using the API from the project [lanqian528/chat2api](https://github.com/lanqian528/chat2api)

```
self@c1 1> /model
                                                                                                     Provider: chat_openai, model: gpt-4o-mini
 n: 1
 openai_api_base: http://192.168.1.154:5005/v1
 openai_api_key:
 temperature: 0.7
```

```
/config
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                            Backend configuration: api                                                                                                            ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                                File configuration                                                                                                                ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

 • Config dir: /root/.config/llm-workflow-engine
 • Config profile dir: /root/.config/llm-workflow-engine/profiles/default
 • Config file: /root/.config/llm-workflow-engine/profiles/default/config.yaml
 • Data dir: /root/.local/share/llm-workflow-engine
 • Data profile dir: /root/.local/share/llm-workflow-engine/profiles/default
 • Database: sqlite:////root/.local/share/llm-workflow-engine/profiles/default/storage.db
 • Cache dirs:
    • /root/.local/share/llm-workflow-engine/cache
 • Template dirs:
    • /root/.config/llm-workflow-engine/profiles/default/templates
    • /root/.config/llm-workflow-engine/templates
 • Preset dirs:
    • /root/.config/llm-workflow-engine/presets
    • /root/.config/llm-workflow-engine/profiles/default/presets
 • Workflow dirs:
    • /root/.config/llm-workflow-engine/workflows
    • /root/.config/llm-workflow-engine/profiles/default/workflows
 • Tool dirs:
    • /root/.config/llm-workflow-engine/tools
    • /root/.config/llm-workflow-engine/profiles/default/tools

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                         Profile 'default' configuration:                                                                                                         ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


 backend: api
 backend_options:
   auto_create_first_user: null
   default_conversation_id: null
   default_user: null
   title_generation:
     model: null
     provider: null
 chat:
   log:
     enabled: false
     filepath: lwe.log
 database: sqlite:////root/.local/share/llm-workflow-engine/profiles/default/storage.db
 debug:
   log:
     enabled: false
     filepath: /tmp/lwe-debug.log
     format: '%(name)s - %(asctime)s - %(levelname)s - %(message)s'
     level: DEBUG
 directories:
   cache:
   - /root/.local/share/llm-workflow-engine/cache
   plugins:
   - /root/.config/llm-workflow-engine/profiles/default/plugins
   - /root/.config/llm-workflow-engine/plugins
   presets:
   - /root/.config/llm-workflow-engine/presets
   - /root/.config/llm-workflow-engine/profiles/default/presets
   templates:
   - /root/.config/llm-workflow-engine/profiles/default/templates
   - /root/.config/llm-workflow-engine/templates
   tools:
   - /root/.config/llm-workflow-engine/tools
   - /root/.config/llm-workflow-engine/profiles/default/tools
   workflows:
   - /root/.config/llm-workflow-engine/workflows
   - /root/.config/llm-workflow-engine/profiles/default/workflows
 log:
   console:
     format: '%(name)s - %(levelname)s - %(message)s'
     level: ERROR
 model:
   default_preset: c1
   default_system_message: default
   system_message:
     creative_writer: You are a creative writing assistant.
     default: You are a helpful assistant.
     programmer: You are an expert programmer, who responds to questions with brief
       examples in code.
 plugins:
   echo:
     response:
       prefix: Echo
   enabled:
   - echo
   - examples
   examples:
     confirm_overwrite: true
     default_types:
     - presets
     - templates
     - workflows
     - tools
   provider_chat_openai: {}
 shell:
   history_file: /tmp/repl_history.log
   prompt_prefix: '$TITLE$NEWLINE($TEMPERATURE/$MAX_SUBMISSION_TOKENS/$CURRENT_CONVERSATION_TOKENS):
     $SYSTEM_MESSAGE_ALIAS$NEWLINE$USER@$PRESET_OR_MODEL'
   streaming: true


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                              Runtime configuration                                                                                                               ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

 • Streaming: True
 • Logging to: None
 • Max submission tokens: 131072
 • System message: You are a helpful assistant.
```

**Comment by thehunmonkgroup** [comment]
Do you have an OpenAI API key configured for API calls to the *actual* OpenAI API?

If you examine the error message, you'll see that the error is generated by the thread that creates a title for the conversation. By default, that uses gpt-3.5-turbo from the official OpenAI API -- you obviously need a valid OpenAI API key for that to work.

You also have the option to set a custom provider and model for generating titles in the config:

```yaml
backend_options:
  title_generation:
    provider: openrouter
    model: "meta-llama/llama-3.1-8b-instruct:free"
plugins:
  enabled:
    - provider_openrouter
```

In that example above, you would need to install the Openrouter provider plugin: https://github.com/llm-workflow-engine/lwe-plugin-provider-openrouter

**Comment by LakeishaKowalczyk** [comment]
@thehunmonkgroup 
Are you asking if I configured the valid key correctly in the chat2api project? The setup for chat2api should be fine since I've been using it for a while. 
Actually, conversations can happen in the llm-workflow-engine too, but only for the first message. After the first one ends successfully, the error pops up.

![图片](https://github.com/user-attachments/assets/15dbe8dc-c335-462a-8cde-0d187fba0c6c)

**Comment by thehunmonkgroup** [comment]
> Are you asking if I configured the valid key correctly in the chat2api project?

No, I'm asking if you have an **OpenAI API key** as obtained here: https://platform.openai.com/settings/profile?tab=api-keys

Conversations must have titles. The default behavior assumes you have a valid OpenAI API setup. If you do not, then you can use an alternate provider/model for your title generation as I specified above.

I suggest you read the project's documentation and/or find a competent programmer to help you with this issue, it is not an issue with the project.
