### ISSUE TITLE
The popup to log in does not appear 

### ISSUE THREAD

**Issue by Cletip** [mmabrouk/chatgpt-wrapper#28]
Hello !
After having made the command "pip install git+https://github.com/mmabrouk/chatgpt-wrapper" which seems to work, I make the command "chatgpt install".

Then, I have the following message: 

```
Install mode: Log in to ChatGPT in the browser that pops up, and click
through all the dialogs, etc. Once that is acheived, exit and restart
this program without the 'install' parameter.

Traceback (most recent call last):
  File "/home/utilisateur/.local/bin/chatgpt", line 8, in <module>
    sys.exit(main())
  File "/home/utilisateur/.local/lib/python3.8/site-packages/chatgpt_wrapper/chatgpt.py", line 379, in main
    chatgpt = ChatGPT(headless=not install_mode)
  File "/home/utilisateur/.local/lib/python3.8/site-packages/chatgpt_wrapper/chatgpt.py", line 38, in __init__
    self.browser = self.play.firefox.launch_persistent_context(
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 13091, in launch_persistent_context
    self._sync(
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 155, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/home/utilisateur/.local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /home/utilisateur/.cache/ms-playwright/firefox-1364/firefox/firefox
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════
```

Maybe the problem is that I am using a browser that is not chrome ?

Sorry, this may be a silly question, but if anyone could point me in the right direction ^^

**Comment by Tecuya** [comment]
You'll want to run `playwright install firefox` to tell playwright to install firefox.  That should resolve this issue.

If you just run `playwright install` as instructed by the message you pasted that will work too, but it will download other browsers that this script does not require.  This script just requires that you install firefox within playwright.

**Comment by Cletip** [comment]
Okay, I understand. 
It works perfectly, but you need to have the browser already installed I think.
Thanks for answering me!
