### ISSUE TITLE
ImportError on run

### ISSUE THREAD

**Issue by blksith0** [mmabrouk/chatgpt-wrapper#296]
Everything was fine until I decided to upgrade.
`pip uninstall chatgpt`
`pip install git+https://github.com/mmabrouk/chatgpt-wrapper`

And now `chatgpt` results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 5, in <module>
    from chatgpt_wrapper.main import main
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/__init__.py", line 1, in <module>
    from chatgpt_wrapper.backends.openai.api import OpenAIAPI
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/backends/openai/api.py", line 10, in <module>
    from chatgpt_wrapper.core.backend import Backend
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/core/backend.py", line 4, in <module>
    from langchain.callbacks.base import CallbackManager
ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks.base' (/usr/local/lib/python3.11/site-packages/langchain/callbacks/base.py)
```

**Comment by thehunmonkgroup** [comment]
No idea what that second error is, looks like an issue w/ your Python install.

Langchain decided to completely rewrite their callback handling, which causes the first error. I've committed a changed to restrict langchain to a version before their refactor. If you reinstall with that first set of  commands, that error should be resolved.

**Comment by blksith0** [comment]
Yup, that fixed it. Thanks.
