### ISSUE TITLE
TypeError when attempting to run in fresh conda environment

### ISSUE THREAD

**Issue by klebs6** [mmabrouk/chatgpt-wrapper#313]
greetings! thanks for everything you folks are creating over here with this project! I love working with it!

Currently, I am trying to upgrade the version and reinstall everything. I hit a bug with the `chatgpt` command after rebuilding the conda environment I am using to run the program :(

any idea what might be going wrong?

I am unsure whether this is an issue in my conda environment setup.  If so, my apologies in advance.  

Suspicious looking to me is the fact that python3.9 seems to be mentioned in the error message even though `python --version` indicates 3.10 as expected.  I am not sure why this is happening, or whether or not it is related to the error I am encountering.

**Describe the bug**
running `chatgpt` in my conda environment gives a TypeError

**To Reproduce**
(see below)

**Expected behavior**
expected to drop into the chatgpt shell without any errors.

**Additional context**

I seem to encounter the same error whether I install from the source repo or with `pip install git+https://github.com/mmabrouk/chatgpt-wrapper`

Here are some steps I have tried, and the resulting output:

```
(base) > $ conda env remove -n gpt                                                                                                                                           [±master ●●]

Remove all packages in environment /Users/kleb/opt/anaconda3/envs/gpt:


kleb@klebs-MacBook-Pro /tmp
(base) > $ conda create --name gpt python=3.10                                                                                                                               [±master ●●]
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/kleb/opt/anaconda3/envs/gpt

  added / updated specs:
    - python=3.10


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  ca-certificates    pkgs/main/osx-64::ca-certificates-2023.05.30-hecd8cb5_0
  libffi             pkgs/main/osx-64::libffi-3.4.4-hecd8cb5_0
  ncurses            pkgs/main/osx-64::ncurses-6.4-hcec6c5f_0
  openssl            pkgs/main/osx-64::openssl-3.0.8-hca72f7f_0
  pip                pkgs/main/osx-64::pip-23.1.2-py310hecd8cb5_0
  python             pkgs/main/osx-64::python-3.10.11-h5ee71fb_3
  readline           pkgs/main/osx-64::readline-8.2-hca72f7f_0
  setuptools         pkgs/main/osx-64::setuptools-67.8.0-py310hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.41.2-h6c40b1e_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  wheel              pkgs/main/osx-64::wheel-0.38.4-py310hecd8cb5_0
  xz                 pkgs/main/osx-64::xz-5.4.2-h6c40b1e_0
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4dc903c_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate gpt
#
# To deactivate an active environment, use
#
#     $ conda deactivate


kleb@klebs-MacBook-Pro /tmp
(base) > $ conda activate gpt                                                                                                                                                [±master ●●]

kleb@klebs-MacBook-Pro /tmp
(gpt) > $ cd /tmp/chatgpt-wrapper                                                                                                                                            [±master ●●]

kleb@klebs-MacBook-Pro /tmp/chatgpt-wrapper                                                                                                                                    [17:28:28]
(gpt) > $ ls                                                                                                                                                                    [±main ✓]
COMMIT_LOG.md        LWE.md               SUPPORT.md           config.sample.yaml   examples             requirements.txt     tests
Dockerfile           License              __init__.py          docker-compose.yml   lwe                  scripts
ISSUES.md            README.md            chatGPT.egg-info     docker-entrypoint.sh postinstall.sh       setup.py

kleb@klebs-MacBook-Pro /tmp/chatgpt-wrapper                                                                                                                                    [17:28:29]
(gpt) > $ pip install -e .                                                                                                                                                      [±main ✓]
Obtaining file:///private/tmp/chatgpt-wrapper
  Preparing metadata (setup.py) ... done
Collecting ansible>=8.0 (from chatGPT==0.12.2)
  Using cached ansible-8.0.0-py3-none-any.whl (42.2 MB)
Collecting ansible-core>=2.15 (from chatGPT==0.12.2)
  Using cached ansible_core-2.15.0-py3-none-any.whl (2.2 MB)
Collecting alembic (from chatGPT==0.12.2)
  Using cached alembic-1.11.1-py3-none-any.whl (224 kB)
Collecting ai21>=1.0.5 (from chatGPT==0.12.2)
  Using cached ai21-1.1.4-py3-none-any.whl
Collecting beautifulsoup4 (from chatGPT==0.12.2)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting cohere>=4.3.1 (from chatGPT==0.12.2)
  Using cached cohere-4.11.2-py3-none-any.whl (39 kB)
Collecting email-validator (from chatGPT==0.12.2)
  Using cached email_validator-2.0.0.post2-py3-none-any.whl (31 kB)
Collecting Flask (from chatGPT==0.12.2)
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting huggingface-hub>=0.13.2 (from chatGPT==0.12.2)
  Using cached huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
Collecting Jinja2 (from chatGPT==0.12.2)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting langchain==0.0.199 (from chatGPT==0.12.2)
  Using cached langchain-0.0.199-py3-none-any.whl (1.0 MB)
Collecting names (from chatGPT==0.12.2)
  Using cached names-0.3.0-py3-none-any.whl
Collecting numexpr>=2.8.4 (from chatGPT==0.12.2)
  Using cached numexpr-2.8.4-cp310-cp310-macosx_10_9_x86_64.whl (99 kB)
Collecting openai>=0.27.2 (from chatGPT==0.12.2)
  Using cached openai-0.27.8-py3-none-any.whl (73 kB)
Collecting openpyxl (from chatGPT==0.12.2)
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting pdfminer.six (from chatGPT==0.12.2)
  Using cached pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
Collecting playwright (from chatGPT==0.12.2)
  Using cached playwright-1.35.0-py3-none-macosx_10_13_x86_64.whl (32.9 MB)
Collecting prompt-toolkit (from chatGPT==0.12.2)
  Using cached prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)
Collecting pydantic-computed (from chatGPT==0.12.2)
  Using cached pydantic_computed-0.2.2-py3-none-any.whl (4.6 kB)
Collecting pyperclip (from chatGPT==0.12.2)
  Using cached pyperclip-1.8.2-py3-none-any.whl
Collecting python-frontmatter (from chatGPT==0.12.2)
  Using cached python_frontmatter-1.0.0-py3-none-any.whl (9.0 kB)
Collecting PyYAML (from chatGPT==0.12.2)
  Using cached PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl (197 kB)
Collecting rich (from chatGPT==0.12.2)
  Using cached rich-13.4.2-py3-none-any.whl (239 kB)
Collecting textract (from chatGPT==0.12.2)
  Using cached textract-1.6.5-py3-none-any.whl (23 kB)
Collecting sqlalchemy<=2,>=1.4.48 (from chatGPT==0.12.2)
  Using cached SQLAlchemy-2.0.0-cp310-cp310-macosx_10_9_x86_64.whl (1.9 MB)
Collecting tiktoken (from chatGPT==0.12.2)
  Using cached tiktoken-0.4.0-cp310-cp310-macosx_10_9_x86_64.whl (797 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached aiohttp-3.8.4-cp310-cp310-macosx_10_9_x86_64.whl (358 kB)
Collecting async-timeout<5.0.0,>=4.0.0 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting dataclasses-json<0.6.0,>=0.5.7 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached dataclasses_json-0.5.8-py3-none-any.whl (26 kB)
Collecting langchainplus-sdk>=0.0.9 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached langchainplus_sdk-0.0.10-py3-none-any.whl (21 kB)
Collecting numpy<2,>=1 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached numpy-1.25.0-cp310-cp310-macosx_10_9_x86_64.whl (20.1 MB)
Collecting openapi-schema-pydantic<2.0,>=1.2 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
Collecting pydantic<2,>=1 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached pydantic-1.10.9-cp310-cp310-macosx_10_9_x86_64.whl (2.9 MB)
Collecting requests<3,>=2 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tenacity<9.0.0,>=8.1.0 (from langchain==0.0.199->chatGPT==0.12.2)
  Using cached tenacity-8.2.2-py3-none-any.whl (24 kB)
Collecting cryptography (from ansible-core>=2.15->chatGPT==0.12.2)
  Using cached cryptography-41.0.1-cp37-abi3-macosx_10_12_x86_64.whl (2.8 MB)
Collecting packaging (from ansible-core>=2.15->chatGPT==0.12.2)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting resolvelib<1.1.0,>=0.5.3 (from ansible-core>=2.15->chatGPT==0.12.2)
  Using cached resolvelib-1.0.1-py2.py3-none-any.whl (17 kB)
Collecting backoff<3.0,>=2.0 (from cohere>=4.3.1->chatGPT==0.12.2)
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting importlib_metadata<7.0,>=6.0 (from cohere>=4.3.1->chatGPT==0.12.2)
  Using cached importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting filelock (from huggingface-hub>=0.13.2->chatGPT==0.12.2)
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting fsspec (from huggingface-hub>=0.13.2->chatGPT==0.12.2)
  Using cached fsspec-2023.6.0-py3-none-any.whl (163 kB)
Collecting tqdm>=4.42.1 (from huggingface-hub>=0.13.2->chatGPT==0.12.2)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.13.2->chatGPT==0.12.2)
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting MarkupSafe>=2.0 (from Jinja2->chatGPT==0.12.2)
  Using cached MarkupSafe-2.1.3-cp310-cp310-macosx_10_9_x86_64.whl (13 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy<=2,>=1.4.48->chatGPT==0.12.2)
  Using cached greenlet-2.0.2-cp310-cp310-macosx_10_9_x86_64.whl
Collecting Mako (from alembic->chatGPT==0.12.2)
  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->chatGPT==0.12.2)
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting dnspython>=2.0.0 (from email-validator->chatGPT==0.12.2)
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Collecting idna>=2.0.0 (from email-validator->chatGPT==0.12.2)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting Werkzeug>=2.3.3 (from Flask->chatGPT==0.12.2)
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting itsdangerous>=2.1.2 (from Flask->chatGPT==0.12.2)
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3 (from Flask->chatGPT==0.12.2)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting blinker>=1.6.2 (from Flask->chatGPT==0.12.2)
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting et-xmlfile (from openpyxl->chatGPT==0.12.2)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Collecting charset-normalizer>=2.0.0 (from pdfminer.six->chatGPT==0.12.2)
  Using cached charset_normalizer-3.1.0-cp310-cp310-macosx_10_9_x86_64.whl (124 kB)
Collecting pyee==9.0.4 (from playwright->chatGPT==0.12.2)
  Using cached pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Collecting wcwidth (from prompt-toolkit->chatGPT==0.12.2)
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting markdown-it-py>=2.2.0 (from rich->chatGPT==0.12.2)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->chatGPT==0.12.2)
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting argcomplete~=1.10.0 (from textract->chatGPT==0.12.2)
  Using cached argcomplete-1.10.3-py2.py3-none-any.whl (36 kB)
Collecting beautifulsoup4 (from chatGPT==0.12.2)
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting chardet==3.* (from textract->chatGPT==0.12.2)
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting docx2txt~=0.8 (from textract->chatGPT==0.12.2)
  Using cached docx2txt-0.8-py3-none-any.whl
Collecting extract-msg<=0.29.* (from textract->chatGPT==0.12.2)
  Using cached extract_msg-0.28.7-py2.py3-none-any.whl (69 kB)
Collecting pdfminer.six (from chatGPT==0.12.2)
  Using cached pdfminer.six-20191110-py2.py3-none-any.whl (5.6 MB)
Collecting python-pptx~=0.6.18 (from textract->chatGPT==0.12.2)
  Using cached python_pptx-0.6.21-py3-none-any.whl
Collecting six~=1.12.0 (from textract->chatGPT==0.12.2)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting SpeechRecognition~=3.8.1 (from textract->chatGPT==0.12.2)
  Using cached SpeechRecognition-3.8.1-py2.py3-none-any.whl (32.8 MB)
Collecting xlrd~=1.2.0 (from textract->chatGPT==0.12.2)
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting pycryptodome (from pdfminer.six->chatGPT==0.12.2)
  Using cached pycryptodome-3.18.0-cp35-abi3-macosx_10_9_x86_64.whl (1.6 MB)
Collecting sortedcontainers (from pdfminer.six->chatGPT==0.12.2)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting regex>=2022.1.18 (from tiktoken->chatGPT==0.12.2)
  Using cached regex-2023.6.3-cp310-cp310-macosx_10_9_x86_64.whl (294 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.199->chatGPT==0.12.2)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.199->chatGPT==0.12.2)
  Using cached multidict-6.0.4-cp310-cp310-macosx_10_9_x86_64.whl (29 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.199->chatGPT==0.12.2)
  Using cached yarl-1.9.2-cp310-cp310-macosx_10_9_x86_64.whl (65 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.199->chatGPT==0.12.2)
  Using cached frozenlist-1.3.3-cp310-cp310-macosx_10_9_x86_64.whl (35 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4.0.0,>=3.8.3->langchain==0.0.199->chatGPT==0.12.2)
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting marshmallow<4.0.0,>=3.3.0 (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.199->chatGPT==0.12.2)
  Using cached marshmallow-3.19.0-py3-none-any.whl (49 kB)
Collecting marshmallow-enum<2.0.0,>=1.5.1 (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.199->chatGPT==0.12.2)
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting typing-inspect>=0.4.0 (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.199->chatGPT==0.12.2)
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting imapclient==2.1.0 (from extract-msg<=0.29.*->textract->chatGPT==0.12.2)
  Using cached IMAPClient-2.1.0-py2.py3-none-any.whl (73 kB)
Collecting olefile>=0.46 (from extract-msg<=0.29.*->textract->chatGPT==0.12.2)
  Using cached olefile-0.46-py2.py3-none-any.whl
Collecting tzlocal>=2.1 (from extract-msg<=0.29.*->textract->chatGPT==0.12.2)
  Using cached tzlocal-5.0.1-py3-none-any.whl (20 kB)
Collecting compressed-rtf>=1.0.6 (from extract-msg<=0.29.*->textract->chatGPT==0.12.2)
  Using cached compressed_rtf-1.0.6-py3-none-any.whl
Collecting ebcdic>=1.1.1 (from extract-msg<=0.29.*->textract->chatGPT==0.12.2)
  Using cached ebcdic-1.1.1-py2.py3-none-any.whl (128 kB)
Collecting zipp>=0.5 (from importlib_metadata<7.0,>=6.0->cohere>=4.3.1->chatGPT==0.12.2)
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->chatGPT==0.12.2)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting lxml>=3.1.0 (from python-pptx~=0.6.18->textract->chatGPT==0.12.2)
  Using cached lxml-4.9.2-cp310-cp310-macosx_10_15_x86_64.whl (4.7 MB)
Collecting Pillow>=3.3.2 (from python-pptx~=0.6.18->textract->chatGPT==0.12.2)
  Using cached Pillow-9.5.0-cp310-cp310-macosx_10_10_x86_64.whl (3.4 MB)
Collecting XlsxWriter>=0.5.7 (from python-pptx~=0.6.18->textract->chatGPT==0.12.2)
  Using cached XlsxWriter-3.1.2-py3-none-any.whl (153 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2->langchain==0.0.199->chatGPT==0.12.2)
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2->langchain==0.0.199->chatGPT==0.12.2)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting cffi>=1.12 (from cryptography->ansible-core>=2.15->chatGPT==0.12.2)
  Using cached cffi-1.15.1-cp310-cp310-macosx_10_9_x86_64.whl (179 kB)
Collecting pycparser (from cffi>=1.12->cryptography->ansible-core>=2.15->chatGPT==0.12.2)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.199->chatGPT==0.12.2)
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: wcwidth, SpeechRecognition, sortedcontainers, resolvelib, pyperclip, names, ebcdic, docx2txt, compressed-rtf, chardet, argcomplete, zipp, XlsxWriter, xlrd, urllib3, tzlocal, typing-extensions, tqdm, tenacity, soupsieve, six, regex, PyYAML, pygments, pycryptodome, pycparser, prompt-toolkit, Pillow, packaging, olefile, numpy, mypy-extensions, multidict, mdurl, MarkupSafe, lxml, itsdangerous, idna, greenlet, fsspec, frozenlist, filelock, et-xmlfile, dnspython, click, charset-normalizer, certifi, blinker, backoff, attrs, async-timeout, yarl, Werkzeug, typing-inspect, sqlalchemy, requests, python-pptx, python-frontmatter, pyee, pydantic, pdfminer.six, openpyxl, numexpr, marshmallow, markdown-it-py, Mako, Jinja2, importlib_metadata, imapclient, email-validator, cffi, beautifulsoup4, aiosignal, tiktoken, rich, pydantic-computed, playwright, openapi-schema-pydantic, marshmallow-enum, langchainplus-sdk, huggingface-hub, Flask, extract-msg, cryptography, alembic, aiohttp, ai21, textract, openai, dataclasses-json, cohere, ansible-core, langchain, ansible, chatGPT
  Running setup.py develop for chatGPT
Successfully installed Flask-2.3.2 Jinja2-3.1.2 Mako-1.2.4 MarkupSafe-2.1.3 Pillow-9.5.0 PyYAML-6.0 SpeechRecognition-3.8.1 Werkzeug-2.3.6 XlsxWriter-3.1.2 ai21-1.1.4 aiohttp-3.8.4 aiosignal-1.3.1 alembic-1.11.1 ansible-8.0.0 ansible-core-2.15.0 argcomplete-1.10.3 async-timeout-4.0.2 attrs-23.1.0 backoff-2.2.1 beautifulsoup4-4.8.2 blinker-1.6.2 certifi-2023.5.7 cffi-1.15.1 chardet-3.0.4 charset-normalizer-3.1.0 chatGPT-0.12.2 click-8.1.3 cohere-4.11.2 compressed-rtf-1.0.6 cryptography-41.0.1 dataclasses-json-0.5.8 dnspython-2.3.0 docx2txt-0.8 ebcdic-1.1.1 email-validator-2.0.0.post2 et-xmlfile-1.1.0 extract-msg-0.28.7 filelock-3.12.2 frozenlist-1.3.3 fsspec-2023.6.0 greenlet-2.0.2 huggingface-hub-0.15.1 idna-3.4 imapclient-2.1.0 importlib_metadata-6.6.0 itsdangerous-2.1.2 langchain-0.0.199 langchainplus-sdk-0.0.10 lxml-4.9.2 markdown-it-py-3.0.0 marshmallow-3.19.0 marshmallow-enum-1.5.1 mdurl-0.1.2 multidict-6.0.4 mypy-extensions-1.0.0 names-0.3.0 numexpr-2.8.4 numpy-1.25.0 olefile-0.46 openai-0.27.8 openapi-schema-pydantic-1.2.4 openpyxl-3.1.2 packaging-23.1 pdfminer.six-20191110 playwright-1.35.0 prompt-toolkit-3.0.38 pycparser-2.21 pycryptodome-3.18.0 pydantic-1.10.9 pydantic-computed-0.2.2 pyee-9.0.4 pygments-2.15.1 pyperclip-1.8.2 python-frontmatter-1.0.0 python-pptx-0.6.21 regex-2023.6.3 requests-2.31.0 resolvelib-1.0.1 rich-13.4.2 six-1.12.0 sortedcontainers-2.4.0 soupsieve-2.4.1 sqlalchemy-2.0.0 tenacity-8.2.2 textract-1.6.5 tiktoken-0.4.0 tqdm-4.65.0 typing-extensions-4.6.3 typing-inspect-0.9.0 tzlocal-5.0.1 urllib3-2.0.3 wcwidth-0.2.6 xlrd-1.2.0 yarl-1.9.2 zipp-3.15.0

kleb@klebs-MacBook-Pro /tmp/chatgpt-wrapper                                                                                                                                    [17:29:52]
(gpt) > $ chatgpt                                                                                                                                                               [±main ✓]
Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 5, in <module>
    from lwe.main import main
  File "/usr/local/lib/python3.9/site-packages/lwe/__init__.py", line 1, in <module>
    from lwe.backends.api.backend import ApiBackend
  File "/usr/local/lib/python3.9/site-packages/lwe/backends/api/backend.py", line 5, in <module>
    from langchain.chat_models.openai import ChatOpenAI
  File "/usr/local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/usr/local/lib/python3.9/site-packages/langchain/tools/__init__.py", line 10, in <module>
    from langchain.tools.bing_search.tool import BingSearchResults, BingSearchRun
  File "/usr/local/lib/python3.9/site-packages/langchain/tools/bing_search/__init__.py", line 3, in <module>
    from langchain.tools.bing_search.tool import BingSearchResults, BingSearchRun
  File "/usr/local/lib/python3.9/site-packages/langchain/tools/bing_search/tool.py", line 10, in <module>
    from langchain.utilities.bing_search import BingSearchAPIWrapper
  File "/usr/local/lib/python3.9/site-packages/langchain/utilities/__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "/usr/local/lib/python3.9/site-packages/langchain/utilities/apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "/usr/local/lib/python3.9/site-packages/langchain/document_loaders/__init__.py", line 45, in <module>
    from langchain.document_loaders.github import GitHubIssuesLoader
  File "/usr/local/lib/python3.9/site-packages/langchain/document_loaders/github.py", line 37, in <module>
    class GitHubIssuesLoader(BaseGitHubLoader):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

(gpt) > $ python --version                                                                                                                                                      [±main ●]
Python 3.10.11
```

**Comment by klebs6** [comment]
sure enough, it was an error in my conda environment!

I was able to fix it by cleaning the whole world and reinstalling from scratch!

**Comment by joshcho** [comment]
the solution is https://github.com/langchain-ai/langchain/issues/7548, you need to update pydantic via `pip install pydantic==1.10.8`
