### ISSUE TITLE
Unusable responses after a session has expired

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#33]
I just tried to use chatgpt this afternoon. Every time I'd send a prompt, I'd immediately get a message about the program receiving an unusable response from ChatGPT. Apparently at some point they'd expired my session, and even the Session command was unable to determine this, it kept saying the session appears to be usable. I had to do a chatgpt install and log in again, at which point it worked. Unfortunately I have no way of knowing just what response the program was receiving from ChatGPT, and since I've already logged in again, I can't debug this further.

**Comment by Tecuya** [comment]
ChatGPT is very unreliable right now.  Requests are hanging forever, and producing error responses.  They are also requiring that you re-login very frequently.  

There are some changes I can make to handle some of these error conditions better, but ultimately I think your issue is probably due to these current conditions.  

* I want to add a timeout so requests to chatGPT that hang forever do not hang the program forever
* When error messages are returned from the requests maybe I can show the raw body of the response or something so we cad see any error messages that ChatGPT is returning to us

**Comment by Tecuya** [comment]
There are improvements to the error messages I want to make that might help a little.  

* I want to make it so requests to chatgpt that hang forever will time out instead of hanging the program forever
* When we do get error http response codes from chatgpt, i should make it say "ChatGPT returned an error"

The `session` command is never going to be able to tell you with 100% certainty whether or not your prompts are going to work.  When it says the session is usable, it only means that your session contains the necessary bearer token to authenticate requests to the conversation API.  This doesn't mean that ChatGPT is actually going to honor that token and respond to prompts..

I'll see if there's anything I can do to detect these sessions that appear valid but are actually not valid.. maybe I can look for an expiration date or something..

**Comment by jaybird110127** [comment]
Earlier today, and also just now, I ran chatgpt and got a huge traceback before the first input prompt ever appeared. Unfortunately I don't have the whole thing, but the last line is: playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation. Is this a problem at your end, or at Playwright's end, or with the ChatGPT servers?

**Comment by Tecuya** [comment]
I've seen that too.  I presume ChatGPT is redirecting the browser to log in, or to an error page, or something.  I haven't figured out the exact cause.

**Comment by HaroldPetersInskipp** [comment]
Same issue here, here is the traceback:

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\chatgpt.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 570, in main
    shell.cmdloop()
  File "C:\Python39\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python39\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Python39\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 365, in do_ask
    return self.default(line)
  File "C:\Python39\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 372, in default
    for chunk in self.chatgpt.ask_stream(line):
  File "C:\Python39\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 107, in ask_stream
    self.refresh_session()
  File "C:\Python39\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 72, in refresh_session
    self.page.evaluate(
  File "C:\Python39\lib\site-packages\playwright\sync_api\_generated.py", line 8584, in evaluate
    self._sync(
  File "C:\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\Python39\lib\site-packages\playwright\_impl\_page.py", line 407, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "C:\Python39\lib\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "C:\Python39\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Python39\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Python39\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation

**Comment by mmabrouk** [comment]
The problem should have been fixed in #153
