### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by mindgitrwx** [mmabrouk/chatgpt-wrapper#39]
I installed it successfully, but 'chatgpt' command provided this error.

```
Traceback (most recent call last):
  File "~/Library/Python/3.9/bin/chatgpt", line 5, in <module>
    from chatgpt.cli import app
  File "~/Library/Python/3.9/lib/python/site-packages/chatgpt/__init__.py", line 1, in <module>
    from . import api
  File "~/Library/Python/3.9/lib/python/site-packages/chatgpt/api.py", line 11, in <module>
    from chatgpt import payloads
  File "~/Library/Python/3.9/lib/python/site-packages/chatgpt/payloads.py", line 5, in <module>
    message: str, id_: str, conv_id: str | None, parent_msg_id: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by Tecuya** [comment]
You have [this other chatgpt program](
https://github.com/mbroton/chatgpt-api) installed and when you run `chatgpt` its running that instead.  


Try running

```
python3 ~/Library/Python/3.9/lib/python/site-packages/chatgpt_wrapper/chatgpt.py
```

**Comment by mindgitrwx** [comment]
Solved clearly I removed other chatgpt program.
