### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MANgolmx** [mmabrouk/chatgpt-wrapper#48]
I think I did everything write but when I write "chatgpt install" it shows me:
Traceback (most recent call last):
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.6', 'console_scripts', 'chatgpt')())
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\Scripts\chatgpt-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_wrapper\__init__.py", line 1, in <module>
    from .chatgpt import ChatGPT
  File "C:\Users\misam\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_wrapper\chatgpt.py", line 15, in <module>
    import pyreadline3  # noqa: F401
ModuleNotFoundError: No module named 'pyreadline3'

I think I am just dumb and did smth wrong idk.

**Comment by MANgolmx** [comment]
In 
File "", line x 
should be
File"<frozen importlib._bootstrap>", line x
github deleted it for some reason

**Comment by fireattack** [comment]
The requirements.txt does have 
```
readline; platform_system!="Windows"
pyreadline3; platform_system=="Windows"
```

but for some reason it's not included in the setup.py, which only has 
```py
    install_requires=[
        "playwright",
        "rich",
    ],
```

So, you have to manually install `readline` or `pyreadline3` (if on Windows).

**Comment by thehunmonkgroup** [comment]
pyreadline was removed long ago, closing.
