### ISSUE TITLE
Exception when using ChatGPT class

### ISSUE THREAD

**Issue by delip** [mmabrouk/chatgpt-wrapper#5]
Followed the instructions, but running the example code gives this exception. I am able to use the `chatgpt` interactive shell though.

```
In [1]: from chatgpt_wrapper import ChatGPT

In [2]: bot = ChatGPT()
Starting ... Done

Traceback (most recent call last):
  File "/Users/delip/opt/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 680, in mainloop
    self.interact()
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 665, in interact
    code = self.prompt_for_code()
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 604, in prompt_for_code
    text = self.pt_app.prompt(
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1020, in prompt
    return self.app.run(
  File "/Users/delip/opt/anaconda3/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/Users/delip/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()
  File "/Users/delip/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 583, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

If you suspect this is an IPython 8.2.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

sys:1: RuntimeWarning: coroutine 'Application.run_async' was never awaited
```

**Comment by mmabrouk** [comment]
I am well aware of the issue. The problem lies in that playwright is currently used in sync mode, which makes any code running it in async mode ends with an error. This issue is in the top of my priorities

**Comment by thehunmonkgroup** [comment]
This should be long ago fixed.
