### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by yotam4h** [mmabrouk/chatgpt-wrapper#51]
C:\WINDOWS\system32>chatgpt install
Install mode: Log in to ChatGPT in the browser that pops up, and click
through all the dialogs, etc. Once that is acheived, exit and restart
this program without the 'install' parameter.

Traceback (most recent call last):
  File "C:\Python311\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.6', 'console_scripts', 'chatgpt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\chatgpt_wrapper\chatgpt.py", line 495, in main
    shell.cmdloop()
  File "C:\Python311\Lib\cmd.py", line 108, in cmdloop
    import readline
  File "C:\Python311\Lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
         ^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Python311\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Python311\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Python311\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by JubileusDeus** [comment]
Try to install the missing packages : That's what I did to fix the issue !
