### ISSUE TITLE
Error with playwright

### ISSUE THREAD

**Issue by RapahelS** [mmabrouk/chatgpt-wrapper#76]
Sometimes I receive the following error. I am using ask_stream.

```
Traceback (most recent call last):
  File "/Users/***/Documents/GitHub/***/main.py", line 120, in <module>
    generate_review_by_product_info(product_info)
  File "/Users/***/Documents/GitHub/***/main.py", line 100, in generate_review_by_product_info
    next_chapter = generate_text_with_pbar_stream(prompt)
  File "/Users/***/Documents/GitHub/***/main.py", line 39, in generate_text_with_pbar_stream
    for t in pbar:
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/chatgpt_wrapper/chatgpt.py", line 231, in ask_stream
    self._cleanup_divs()
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/chatgpt_wrapper/chatgpt.py", line 103, in _cleanup_divs
    self.page.evaluate(f"document.getElementById('{self.eof_div_id}').remove()")
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 7697, in evaluate
    self._sync(
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_page.py", line 407, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/opt/anaconda3/envs/mobileComputing/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: document.getElementById(...) is null
@debugger eval code line 191 > eval:1:10
evaluate@debugger eval code:191:30
@debugger eval code:1:44
```

**Comment by thehunmonkgroup** [comment]
Most likely transient, cannot reproduce. Is this still an issue?
