### ISSUE TITLE
cannot switch to a different thread

### ISSUE THREAD

**Issue by LimerBoy** [mmabrouk/chatgpt-wrapper#77]
Python 3.9.0
Win 10

Error:
```
Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe...rget closed')>) at C:\Users\Homee\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright-1.30.0-py3.9-win-amd64.egg\playwright\_impl\_sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe...rget closed')>) at C:\Users\Homee\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright-1.30.0-py3.9-win-amd64.egg\playwright\_impl\_sync_base.py:100>
Traceback (most recent call last):
  File "C:\Users\Homee\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Homee\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright-1.30.0-py3.9-win-amd64.egg\playwright\_impl\_sync_base.py", line 100, in <lambda>
    task.add_done_callback(lambda _: g_self.switch())
greenlet.error: cannot switch to a different thread
```
My code:

```python
from telebot import TeleBot
from chatgpt_wrapper import ChatGPT

chat = ChatGPT()
bot = TeleBot('My token')

@bot.message_handler(func=lambda message: True)
def message(message):
    bot.reply_to(message, chat.ask(message.text))
    
bot.polling()
```

**Comment by brandonrobertz** [comment]
Playwright, the site instrumentation library behind this library, [isn't thread safe](https://playwright.dev/python/docs/intro#threading) in the way you're doing it. In order to use threads you need to instantiate the ChatGPT wrapper separately inside of each thread.

**Comment by MuMuShy** [comment]
I add monkey patch in ChatGPT __init__ function and its work fine for me
```
def __init__(self, headless: bool = True, browser="firefox", timeout=60):
  from gevent import monkey
  monkey.patch_all()
  
```

**Comment by thehunmonkgroup** [comment]
Closing due to inactivity.
