### ISSUE TITLE
Program crash when logging special characters to file.

### ISSUE THREAD

**Issue by CodeZilla12** [mmabrouk/chatgpt-wrapper#97]
Running the wrapper via shell with the !log function toggled causes a crash when appending characters ą,č,ę,ė,į,ų,ū from the lithuanian alphabet. Ž seems to work just fine.

Transcript of  conversations and tracebacks below:

Case 1:
```
2> !log gptLogs.txt

 • Logging enabled, appending to 'gptLogs.txt'.

2> Gali kalbi lietuviškai?

Taip, aš galiu suprasti ir generuoti tekstą lietuvių kalba. Kaip galiu padėti šiandien?

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.13', 'console_scripts', 'chatgpt')())
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 584, in main
    shell.cmdloop()
  File "C:\Program Files\Python39\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Program Files\Python39\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 369, in do_ask
    return self.default(line)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 389, in default
    self._write_log(line, response)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 303, in _write_log
    self.logfile.write(f"{self.prompt_number}> {prompt}\n\n{response}\n\n")
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0105' in position 72: character maps to <undefined>
```
Case 2:
```
3> !log gptLogs.txt

 • Logging enabled, appending to 'gptLogs.txt'.

3> repeat after me: ž

ž

4> repeat after me: ū

ū

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.13', 'console_scripts', 'chatgpt')())
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 584, in main
    shell.cmdloop()
  File "C:\Program Files\Python39\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Program Files\Python39\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 369, in do_ask
    return self.default(line)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 389, in default
    self._write_log(line, response)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\chatgpt_wrapper\chatgpt.py", line 303, in _write_log
    self.logfile.write(f"{self.prompt_number}> {prompt}\n\n{response}\n\n")
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u016b' in position 20: character maps to <undefined>
```

**Comment by mmabrouk** [comment]
Problem should be solved. please reinstall chatgpt and let me know

**Comment by CodeZilla12** [comment]
Works fine now. Thank you!
